### PR TITLE
Fix: add default locale to api create endpoint

### PR DESCRIPTION
**Pull request by robinandeer**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1701** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1701" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1701?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Review by KarnellSchultz — APPROVED** [review]
traveling-lets-go-gif-by-hallmark-channel

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Job ID: jM18V5cH7DbxbGs5OxrV.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1701)

**Pull request merged**
