### PR TITLE
GEN-1232 | Car dealership: use separate translation namespace

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Migrate car dealership translations to separate namespace

## Justify why they are needed

- Make it easier to delete the whole feature

- Avoid adding non-cart translations to the cart namespace

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3303** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3303" target="_blank">Graphite</a> 
    * **PR #3304** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3304" target="_blank">Graphite</a> 
      * **PR #3305** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3305" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3305?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Great idea!

**Review by guilhermespopolin — APPROVED** [review]
Awesome 🚀

**Comment by robinandeer** [comment]
### Merge Activity

* **Oct 2, 1:40 PM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3305).

**Review by gustaveen — APPROVED** [review]
Oh yes! 👌

**Pull request merged**
