### PR TITLE
Skip fetching recommendations with shop session

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Skip fetching product recommendations with every shop session.

Fetch product recommendations on demand after loading the rest of the page (cart).

## Justify why they are needed

Try to speed up loading of the cart page.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1771** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1771" target="_blank">Graphite</a> 
    * **PR #1775** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1775" target="_blank">Graphite</a> 
      * **PR #1776** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1776" target="_blank">Graphite</a> 
        * **PR #1779** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1779" target="_blank">Graphite</a> 
          * **PR #1780** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1780" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1780?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice, should reduce the load

Did you look at `@lazy` graphQL directive as a potential future way to do it?

**Comment by robinandeer** [comment]
@alebedev hmm no I didn't -- do you know if it's supported out of the box?

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Job ID: XN298PhZepSKV8xOFfYG.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1780)

**Pull request merged**
