### PR TITLE
Update theme colors and use legacy theme for onboarding

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Start updating theme with new colors. To not mess up onboarding we can use a theme with the old colors.

~~However TS complains about the typed theme. We declare the emotion Theme interface in onboarding, but it still picks up the type defined in `ui`. Wouldn't typescript look at definitions in the `onboarding` package?~~

## Justify why they are needed
Updated design

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

> Nice stuff!
> 
> Will be interesting to see when we switch over to the new theme how the UI hold up

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1079** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1079" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1079?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Nice stuff!

Will be interesting to see when we switch over to the new theme how the UI hold up

**Comment by gustaveen** [comment]
> Nice stuff!
> 
> Will be interesting to see when we switch over to the new theme how the UI hold up

There will be some tweaking of colors for sure :D

**Review by guilhermespopolin — APPROVED** [review]
💅🏻

**Comment by alebedev** [comment]
Nice!  Is there a way to contain legacyTheme to onboarding app and remove it from ui package?

**Comment by gustaveen** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1079?utm_source=stack-comment).


Job Reference: zB8VYvxqwHaQ4wYqK5TQ

**Pull request merged**
