### PR TITLE
Cart toast: add close button

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Cart toast: replace checkout link with a simple close button

## Justify why they are needed

Design update

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2422** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2422" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2422?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
So, did we decide that "quick buy" is not something we want for better conversion?

No questions to implementation itself

**Comment by robinandeer** [comment]
> So, did we decide that "quick buy" is not something we want for better conversion?
> 
> No questions to implementation itself

Yes we start with this and iterate when we look into cross sales!

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2422).

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2422).

**Pull request merged**
