### PR TITLE
Badge: align props with Figma

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add new color option to the Badge

- Rename Badge sizes to "small" and "big"

## Justify why they are needed

- Match the design system in the Figma file

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3208** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3208" target="_blank">Graphite</a>  👈
    * **PR #3209** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3209" target="_blank">Graphite</a> 
      * **PR #3210** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3210" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3208?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
👌

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Comment by robinandeer** [comment]
### Merge Activity

* **Sep 18, 9:03 AM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3208).

**Pull request merged**
