### PR TITLE
[GEN-550] Update RichText component

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Design updates 
[Figma](https://www.figma.com/file/cVLHYYJ94yLFhq08dnHVpo/Rich-Text?type=design&node-id=221%3A1078&t=szYXErQVvdL67Xbi-1)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2560** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2560" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2560?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Comment by gustaveen** [comment]
@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2560).

**Comment by gustaveen** [comment]
@gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2560).

**Pull request merged**
