### PR TITLE
Widget | Display campaign on confirmation page

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add component to widget confirmation page to show included discount

- Add new hook to get discount from redeemed campaign field in API

## Justify why they are needed

- Implement figma design

- I saw an opportunity to avoid some code duplication

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3583** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3584** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3584?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3586** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3587?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3591** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3591?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3592** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3592?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3593** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3593?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3594** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3594?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3595** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #3596** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3596?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #3597** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #3598** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #3599** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #3600** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3583** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3584** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3584?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3586** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3587?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3591** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3591?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3592** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3592?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3593** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3593?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3594** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3594?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3595** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #3596** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3596?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #3597** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #3598** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #3599** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #3600** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
NIce :)

**Comment by robinandeer** [comment]
### Merge activity

* **Nov 21, 5:02 PM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600).

**Pull request merged**
