### PR TITLE
Add visual scroll to button component for ProductPage

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Add framer-motion as dependency to store app.
Add basic pill button component.
Add example usage in Storybook.

[Screen Recording 2022-08-01 at 17.24.01.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/OgXegTwxM9IeuXHZyw5h/fea3ecb4-7d05-4507-9acc-75718d36a687/Screen%20Recording%202022-08-01%20at%2017.24.01.mov)

## Justify why they are needed

I wanted to create an intuitive API. Please check the Storybook example.

We will probably have to update this since we need to display either the price footer or this scroll-to-button based on if there is a calculated price or not. But at least it shows how I think it could work.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

[GRW-1302]: https://hedvig.atlassian.net/browse/GRW-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #343** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/343" target="_blank">Graphite</a> 
    * **PR #344** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/344" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/344?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Nice :)
At first I was thinking of solving it with [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). However the kind of problem seems different on this case :)

**Review by robinandeer — COMMENTED** [review]
@guilhermespopolin yeah I thought that would cut it also but there's no way that I could think of that takes into consideration if you are above or below the element you are observing...

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/344?utm_source=stack-comment).


Job Reference: dHviibmih86u4jWvOczB

**Pull request merged**
