### PR TITLE
GEN-2782 - feat(cart-discount): added a lingering campaign code feature

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## Describe your changes

Update it so previous added campaign code keep stored until requested to be deleted by clicking on the badge:

https://github.com/user-attachments/assets/f88fd6e9-651a-42ca-b355-11c10c167582

## Justify why they are needed

Requested by design

### CODE REVIEW

**Comment by guilhermespopolin** [comment]
* **#4935** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4935?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @guilhermespopolin and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alebedev — COMMENTED** [review]
1. There're display artifacts when expanding the field - inner content jumps between states
2. We should probably not send undredeem mutation on toggle - I'll initiate Slack discussion

**Comment by guilhermespopolin** [comment]
Closing this as we'll iterate over a better solution in the future.

**Comment by guilhermespopolin** [comment]
Closing this as we'll iterate over a better solution in the future.

**Pull request closed without merging**
