### PR TITLE
Add multi-root VSCode workspace

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Add multi-root VSCode workspace: https://code.visualstudio.com/docs/editor/multi-root-workspaces

Add setup to make vscode-jest work as expected!

Move settings inside workspace file.

## Justify why they are needed

To make vscode-test work.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Review by gustaveen — COMMENTED** [review]
Just looking at the documentation, it sounds resonable for a monorepo https://code.visualstudio.com/docs/editor/workspaces 

What cons could it bring? Couldn't figure out that bit from the docs :)

**Review by robinandeer — COMMENTED** [review]
@gustaveen I think it more has to do with committing editor setup to git

Perhaps someone wants to setup their editor differently and then this would become a problem

**Comment by gustaveen** [comment]
> @gustaveen I think it more has to do with committing editor setup to git
> 
> Perhaps someone wants to setup their editor differently and then this would become a problem

Gotcha! I have to little knowledge on the topic, but it seems that if you add your own `.vscode/settings.json` file you can still override the workspace settings if you like :)

**Review by gustaveen — APPROVED** [review]
Let's try it! 🙌

**Pull request merged**
