### PR TITLE
Add ButtonLink component which uses Next.js Link

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Add utility component to be able to use UI/Button with Next.js Link

## Justify why they are needed

We are already using it in many places - this will reduce boilerplate!

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1193** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1193" target="_blank">Graphite</a>  👈
    * **PR #1194** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1194" target="_blank">Graphite</a> 
      * **PR #1195** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1195" target="_blank">Graphite</a> 
        * **PR #1196** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1196" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1193?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

Is this name consistent. though?  I'd expect LinkButton or NextLinkButton

**Comment by robinandeer** [comment]
@alebedev maybe we should include next

I was thinking about it:

- is this a link styled as a button (ButtonLink)
- is this a button that behaves as a link (LinkButton)

I went with the first but pls disagree 😅

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: 2p15yc9KoO3nPlDemyGK.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1193)

**Review by KarnellSchultz — APPROVED** [review]

**Pull request merged**
