### PR TITLE
ShopBreakdown: break out custom tracking hook

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Separate out a custom hook that tracks views of the cart page

## Justify why they are needed

- Part of implementing ShopBreakdown component

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3010** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
👌

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010) rebased this pull request as part of a merge.

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010).

**Pull request merged**
