### PR TITLE
Move Separate component from UI kit to Onboarding app

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Move Separate component from UI Kit to Onboarding app

## Justify why they are needed

It only used in Onboarding app, so it should be moved there

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2680** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2680" target="_blank">Graphite</a> 
    * **PR #2681** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2681" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2681?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2681).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2681) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2681).

**Pull request merged**
