### PR TITLE
Implement find or create endpoint for session

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Group together ShopSession with Cart in mocks.
Always get cart with ShopSession query.
Remove unused queries/mutations.

## Justify why they are needed

Simplify the client side logic and move this handling to the API.
Client always needs a session to work.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #321** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/321" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/321?utm_source=stack-comment).

**Review by dendoesit — APPROVED** [review]
great work.

**Review by guilhermespopolin — APPROVED** [review]
🛒

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/321?utm_source=stack-comment).


Job Reference: gjKpviQE95hVRnCGYPiY

**Pull request merged**
