### PR TITLE
ShopBreakdown: add edit action button (container)

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add edit product offer action button component with related logic

## Justify why they are needed

- Co-location

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3010** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010" target="_blank">Graphite</a> 
    * **PR #3011** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3011" target="_blank">Graphite</a> 
      * **PR #3012** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3012" target="_blank">Graphite</a> 
        * **PR #3013** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013" target="_blank">Graphite</a> 
          * **PR #3015** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3015" target="_blank">Graphite</a> 
            * **PR #3017** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3017" target="_blank">Graphite</a> 
              * **PR #3018** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3018" target="_blank">Graphite</a> 
                * **PR #3019** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3019" target="_blank">Graphite</a> 
                  * **PR #3021** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3021" target="_blank">Graphite</a> 
                    * **PR #3022** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3022" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3022?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3022).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3022) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3022).

**Pull request merged**
