### PR TITLE
Add story for RichText

### PR DESCRIPTION
**Pull request by gustaveen**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2552** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2552" target="_blank">Graphite</a> 
    * **PR #2554** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2554" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2554?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
[bow](https://app.graphite.dev/macros/HedvigInsurance)

**Comment by gustaveen** [comment]
@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2554).

**Comment by gustaveen** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2554) rebased this pull request as part of a merge.

**Comment by gustaveen** [comment]
@gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2554).

**Pull request merged**
