### PR TITLE
Fix warning about non-boolean attribute passed to DOM element

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Fix warning from `Button` component.

```text
Warning: Received `false` for a non-boolean attribute `loading`.
If you want to write it to the DOM, pass a string instead: loading="false" or loading={value.toString()}.
```

Use data-attribute in favor of passing prop to Emotion component.

Refactor Button to use imported theme rather than provider-theme.

Add mention of required `EDGE_CONFIG` environment variable.

## Justify why they are needed

Using data-attribute we can generate build-time CSS stylesheets rather than creating a runtime style dependency. It's also how Radix works a lot of the time and I kind of like it. CSS is powerful!

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1318** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1318" target="_blank">Graphite</a> 
    * **PR #1319** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1319" target="_blank">Graphite</a> 
      * **PR #1320** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1320" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1320?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Comment by robinandeer** [comment]
@gustaveen haha I think it worked well in this case but we are still passing size as a prop to Button e.g.

Let's see. Perhaps data-attributes make the most sense to communicate "states" of a component rather than different variants.

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: s3qmEzbk8MIL7p5CwkCI.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1320)

**Pull request merged**
