### PR TITLE
Add form template for SE accident

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

See title.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #592** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/592" target="_blank">Graphite</a> 
    * **PR #593** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/593" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/593?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
👌

**Review by alebedev — APPROVED** [review]
Looks good

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/593?utm_source=stack-comment).


Job Reference: qsfJXT0umdPp4CZsc92J

**Pull request merged**
