### PR TITLE
Add reset sesion button to debug dialog

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add button (link) to reset current session from Debug Dialog

- Include alongside shop session ID

## Justify why they are needed

- One of the common operations

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2798** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2798" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2798?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2798).

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2798).

**Pull request merged**
