### PR TITLE
GEN-1138 | BankSignering: fix logging opening link

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Explicit logging of bank signering open action

## Justify why they are needed

- ~I can't find the action in DD, so I'm guessing the "data" attribute doesn't work as expected~

- Datadog doesn't automatically track clicks that lead to a new page being loaded (https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/?tab=npm#track-user-interactions)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3211** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3211" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3211?utm_source=stack-comment).

**Review by alebedev — COMMENTED** [review]
Can we reproduce the problem elsewhere?  It's very nice when attribute-based approach works, so let's try to see where we can rely on it

Maybe it has something to do with `target="_blank"` and the link being external?

**Comment by robinandeer** [comment]
> Can we reproduce the problem elsewhere?  It's very nice when attribute-based approach works, so let's try to see where we can rely on it
> 
> Maybe it has something to do with `target="_blank"` and the link being external?

Very good point! It seems my conclusion was wrong -- data-attributes work as expected. However, in this case we should not expect it to track anything since the click "lead to a new page being loaded" (https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/?tab=npm#track-user-interactions)

So in this case I think it's correct to use a custom action 🙂

**Review by alebedev — APPROVED** [review]
Great, now we know when we need to do custom actions

**Review by guilhermespopolin — APPROVED** [review]
Nice. Good to know about this detail with dd actions.

**Pull request merged**
