### PR TITLE
`CartInventory`: update desktop design

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

I noticed that the desktop design for the cart inventory didn't match figma so I updated it just a little bit.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1301** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1301" target="_blank">Graphite</a> 
    * **PR #1302** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1302" target="_blank">Graphite</a> 
      * **PR #1304** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1304" target="_blank">Graphite</a> 
        * **PR #1305** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1305" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1305?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1301** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1301" target="_blank">Graphite</a> 
    * **PR #1302** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1302" target="_blank">Graphite</a> 
      * **PR #1304** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1304" target="_blank">Graphite</a> 
        * **PR #1305** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1305" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1305?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: gqYL6BIeAxEUO9tXGd8T.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1305)

**Pull request merged**
