### PR TITLE
Car dealership: fix types in fixtures

### PR DESCRIPTION
**Pull request by robinandeer**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3265** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3265" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3265?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
👍

**Review by guilhermespopolin — APPROVED** [review]
ops

**Comment by robinandeer** [comment]
### Merge Activity

* **Sep 26, 9:39 AM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3265).

**Pull request merged**
