### PR TITLE
styles(ProductDetailsPage): remove double scroll

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## Describe your changes

See title ☝🏻 

## Justify why they are needed

It was added [here](https://github.com/HedvigInsurance/racoon/pull/1230/files). Not sure the problem it was trying to fix when it got added. Maybe @robinandeer remembers it?!
Let me know if I'm missing something.

**Before**

Screenshot 2023-03-07 at 11 06 43

**After**
Screenshot 2023-03-07 at 11 10 47

### CODE REVIEW

**Comment by guilhermespopolin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1894** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1894" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1894?utm_source=stack-comment).

**Review by robinandeer — COMMENTED** [review]
@guilhermespopolin the issue is that when you try to scroll in car PDP you can't get to the bottom of the right hand content unless you scroll very far down 🤔 

But I would show this to design and ask which version is preferrable!

**Comment by guilhermespopolin** [comment]
> @guilhermespopolin the issue is that when you try to scroll in car PDP you can't get to the bottom of the right hand content unless you scroll very far down 🤔
> 
> But I would show this to design and ask which version is preferrable!

Ohh I see now. Thanks for the explanation. I thought it was solving an issue that might not be still present, but that's not the case.

**Comment by robinandeer** [comment]
@guilhermespopolin hmm yeah neither solution is very good :P

**Pull request closed without merging**
