### PR TITLE
GEN-2470 - styles(combobox): support size variants (small, medium, large)

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## Describe your changes

* Combobox: support size variants: 'small', 'medium' and 'large'

image

With that change, Breed Selector now has the same sizing styles and other inputs on new Price Calculator pages:

image

## Justify why they are needed

Some of the changes included in Breed Selector [redesign](https://www.figma.com/design/5kmmDdh6StpXzbEfr7WevV/Hedvig-UI-Kit?node-id=15404-12523).

### CODE REVIEW

**Review by alebedev — CHANGES_REQUESTED** [review]
Can we do it with CSS classes and specific selectors, without relying on HTML attributes? I think attributes should be the last solution when everything else fails. Here we're targeting things inside single component, so there's probably no need for attributes

**Comment by guilhermespopolin** [comment]
> Can we do it with CSS classes and specific selectors, without relying on HTML attributes? I think attributes should be the last solution when everything else fails. Here we're targeting things inside single component, so there's probably no need for attributes

Aha, I see. The thing I like about this approach is that every UI related change/decision is under CSS realm. But I can change it by adding specific selectors 👍🏻

**Review by alebedev — APPROVED** [review]
Great!

**Comment by guilhermespopolin** [comment]
### Merge activity

* **Aug 12, 9:08 AM EDT**: @guilhermespopolin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4579).

**Pull request merged**
