### PR TITLE
Add peril colors for pet

### PR DESCRIPTION
**Pull request by robinandeer**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2071** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2071" target="_blank">Graphite</a> 
    * **PR #2076** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2076" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2076?utm_source=stack-comment).

**Comment by gustaveen** [comment]
Oh shoot, I worked on this as well yesterday :D But I added it in PCMS instead, but maybe that doesn't work? @robinandeer

**Comment by robinandeer** [comment]
> Oh shoot, I worked on this as well yesterday :D But I added it in PCMS instead, but maybe that doesn't work? @robinandeer 

hehe yes I heard from Sonny. The current solution doesn't use data from PCMS though -- just hardcoding colors like this.

Guess we need to update API to expose the new color codes -- or have you already fixed that?

**Comment by gustaveen** [comment]
> > Oh shoot, I worked on this as well yesterday :D But I added it in PCMS instead, but maybe that doesn't work? @robinandeer
> 
> hehe yes I heard from Sonny. The current solution doesn't use data from PCMS though -- just hardcoding colors like this.
> 
> Guess we need to update API to expose the new color codes -- or have you already fixed that?

Aha, then I understand :D Have not done that, but I could give it a try :) Where would I update that?

**Review by gustaveen — APPROVED** [review]
Sweet! 🔴

**Review by guilhermespopolin — APPROVED** [review]

**Pull request merged**
