### PR TITLE
Feature / Setup GraphQL codegen

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Here we go again with all the seemingly irrelevant dev dependencies that we just need to run the codegen 🙄

Setup non-Apollo GraphQL client.
Add .env file with defaults.

Setup is similar to onboarding except:

- The graphql endpoint is referenced by env var in the codegen config. This requires us to use a `.env` file. In Next.js this is the file we should use to set default environment variables so I think it fits pretty well :)
- I put a "graphql" folder outside "src" to group all mutation/query definitions -- good/bad?

## Justify why they are needed

Type safety.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Review by guilhermespopolin — APPROVED** [review]
Nice work :)
About the placement for `graphql` folder I think I'd keep it under `src` as we have for `onboarding`. There's no real argument against it; it's just personal preference 😅 
But honestly, both options are fine 😄

**Review by gustaveen — APPROVED** [review]
Great! I think we can put `/graphql` under `src` or do we feel like we want to separate it from the rest of the codebase?

**Review by robinandeer — COMMENTED** [review]
I moved it outside of `/src` since I didn't think it's actual source code 🤔

It's more like config we use to generate the source code -- but I don't mind moving it inside src again :)

**Review by robinandeer — COMMENTED** [review]
Okey I will move it in my next PR!

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/298?utm_source=stack-comment).


Job Reference: Jl1125ldcu9HBt83oi9D

**Pull request merged**
