### PR TITLE
Add feature flag for english locale

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Add feature flag for enabling/disabling the english locale.

Hide language selector if English locale is not available.

## Justify why they are needed

For the launch.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1791** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1791" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1791?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
Cool! Will we only go live with /se?

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@gustaveen yes we will only go live with Swedish site in swedish

**Pull request merged**
