### PR TITLE
Checkout: conditionally show campaigns

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Hide campaigns from Checkout page if API says they are not available.

## Justify why they are needed

Bug fix.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1998** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1998" target="_blank">Graphite</a> 
    * **PR #1999** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1999" target="_blank">Graphite</a> 
      * **PR #2000** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2000" target="_blank">Graphite</a> 
        * **PR #2001** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2001" target="_blank">Graphite</a> 
          * **PR #2004** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2004" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2004?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1998** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1998" target="_blank">Graphite</a> 
    * **PR #1999** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1999" target="_blank">Graphite</a> 
      * **PR #2000** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2000" target="_blank">Graphite</a> 
        * **PR #2001** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2001" target="_blank">Graphite</a> 
          * **PR #2004** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2004" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2004?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2004).

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2004).

**Pull request merged**
