### PR TITLE
Create generic stepper input component

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Break out the generic part from household size field.

## Justify why they are needed

Needed for number of bathrooms field.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1796** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1796" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1796?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
🙌

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Job ID: kYj8jGnf1dcI5M5sz40q.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1796)

**Pull request merged**
