### PR TITLE
Open comparison table in modal

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Open comparison table in modal

https://user-images.githubusercontent.com/6661511/224150480-0f013107-1a9e-400c-811a-263e4bee482d.mov

https://user-images.githubusercontent.com/6661511/224150581-ba31d295-13cc-4265-b020-bcb9b6e60e65.mov

## Justify why they are needed
[Updated design](https://www.figma.com/file/8SfzuQEJ4LJ6uKL0l7WKoE/Hedvig.com-%C2%B7-Final-Design?node-id=5952%3A71242&t=wMdwR8RDFaUTPLg3-1) 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1915** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1915" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1915?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Looks good - the only thing is that the border look strange in desktop :/

[beautiful](https://app.graphite.dev/macros/HedvigInsurance)

**Review by guilhermespopolin — APPROVED** [review]
Looking good 💅🏻

**Comment by gustaveen** [comment]
> Looks good - the only thing is that the border look strange in desktop :/
> 
> [beautiful](https://app.graphite.dev/macros/HedvigInsurance) [ beautiful ](https://app.graphite.dev/macros/HedvigInsurance) [ ](https://app.graphite.dev/macros/HedvigInsurance)

Indeed! Zak is looking over the border color, it needs more black :) @robinandeer

**Pull request merged**
