### PR TITLE
Add support for publishing to Chromatic

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Integrate with the basic version of Chromatic platform to include Storybook in code review process.
https://www.chromatic.com/docs/

## Justify why they are needed

Let's try out this platform. The basic plan is "free forever". It also let's us off load the Storybook deployments from Vercel.

I didn't add "chromatic" as a deployment - better see if we can make it work with just the latest version (using npx).
It's also not a mission critical tool.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

[GRW-1312]: https://hedvig.atlassian.net/browse/GRW-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #350** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/350" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/350?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
🤔 So you have a _chromatic_ account and you've created a project there for `racoon/store`. Then you've generated a project token and stored it as a secret in `racoon`'s repo. And with that configured, on every push (into every branch) a new _chromatic_  build will be generated. Is that correct?

The only thing I'm missing tho is how to access those _chromatic_ builds. I mean, how can 
 I share a link of our most recent version of _Storybook_ with Amy, for example without getting one from a PR.
 Would I need to create an account and be invited for `racoon/store` project inside _chromatic_?

**Review by robinandeer — COMMENTED** [review]
@guilhermespopolin I think you should be able to just login to chromatic and see the project:

> This project currently syncs collaborators from HedvigInsurance/racoon. Collaborators must login to Chromatic to begin syncing and appear in the list.

**Comment by guilhermespopolin** [comment]
> @guilhermespopolin I think you should be able to just login to chromatic and see the project:
> 
> > This project currently syncs collaborators from HedvigInsurance/racoon. Collaborators must login to Chromatic to begin syncing and appear in the list.

Oh, I see the issue. One step was missing from the login process. It's working now :)

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/350?utm_source=stack-comment).


Job Reference: 97Ni5h6J9snBETZbSL6j

**Pull request merged**
