### PR TITLE
Use personal number field in session debugger

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Use personal number field in session debugger to be able to use SSN short format and frontend validation 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4089?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4089** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4089?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4088** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4088?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gustaveen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Youakeem — APPROVED** [review]
Thank you! I wasn't aware of it!

**Comment by gustaveen** [comment]
> Thank you! I wasn't aware of it!

No problem! 🙌

**Comment by gustaveen** [comment]
### Merge activity

* **Mar 22, 5:44 AM EDT**: @gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4089).

**Pull request merged**
