### PR TITLE
ShopBreakdown: add `TotalAmountContainer`

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add container for `TotalAmount` component

## Justify why they are needed

- Co-locate API logic related to the presentational component

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3010** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010" target="_blank">Graphite</a> 
    * **PR #3011** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3011" target="_blank">Graphite</a> 
      * **PR #3012** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3012" target="_blank">Graphite</a> 
        * **PR #3013** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
🤑

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013).

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013).

**Pull request merged**
