### PR TITLE
Add USPs to QuickAdd component

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
- Add USP list to QuickAdd component
Screenshot 2023-12-11 at 17 52 20

## Justify why they are needed
Update accident x-sell project

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3715** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3715?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3716** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3716?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3717** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3717?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3723** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3723?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3723?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Added via Giphy
Starting to look real nice!

**Review by guilhermespopolin — APPROVED** [review]
Every time I see USP I remember Counter Strike 😆  🖥️ 

image

**Comment by gustaveen** [comment]
### Merge activity

* **Dec 14, 4:58 AM**: @@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3723).

**Pull request merged**
