### PR TITLE
Use SSR to render newly published pages

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Turn on `fallback: blocking` setting for CMS pages

## Justify why they are needed

- Allow newly published pages to be server-side rendered immediately (and then cached for subsequent requests). Today, we need to wait for the next build to be deployed before the page is available.

- Read more from the in the [Next.js docs](https://nextjs.org/docs/pages/api-reference/functions/get-static-paths#fallback-blocking)

- Caveat: this setting is not compatible with `FALLBACK_ORIGIN_URL`

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3478** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3478" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3478?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
Eeehhh, fantastic!!! Has this been an option all this time or is it newly added?

**Comment by robinandeer** [comment]
@gustaveen this has always been possible. However, as long as we used Market Web as fallback we couldn't use it :)

I'll leave this PR open until you validated the site with Peter -- feel free to merge when you feel ready!

**Comment by gustaveen** [comment]
### Merge activity

* **Oct 26, 10:43 AM**: @gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3478).

**Pull request merged**
