### PR TITLE
Feature / Add support for basic auth

### PR DESCRIPTION
**Pull request by robinandeer**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #260** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/260" target="_blank">Graphite</a> 
    * **PR #261** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/261" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/261?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
Great! 🗝

**Comment by gustaveen** [comment]
Will we use the same user/pass as before? :)

**Comment by robinandeer** [comment]
> Will we use the same user/pass as before? :)

yep I was gonna use the same

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/261?utm_source=stack-comment).


Job Reference: Fh5gvOSg8Jg6yIMEIGCf

**Pull request merged**
