### PR TITLE
Update story for TrialExtensionForm

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
- Add Grid parameter to adjust width
- Add story for not connected payment

Screenshot 2023-10-03 at 10 53 36

Screenshot 2023-10-03 at 10 53 30

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3315** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3315" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3315?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
[approvedarthvader](https://app.graphite.dev/macros/HedvigInsurance)

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Comment by gustaveen** [comment]
### Merge Activity

* **Oct 9, 8:16 AM**: @gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3315).

**Pull request merged**
