### PR TITLE
ShopBreakdown: implement total amount container on Checkout page

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Implement `TotalAmountContainer` on Checkout page

- Make it a shared component

## Justify why they are needed

- Continue implmenting shop breakdown across app

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3035** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3035" target="_blank">Graphite</a> 
    * **PR #3036** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3036" target="_blank">Graphite</a> 
      * **PR #3037** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3037" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3037?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
👌

**Review by guilhermespopolin — APPROVED** [review]
So now I think I got the full picture: we get the `shopSession` high in the tree in the page component, and them just pass it down via prop so other containers can do something with it instead of each container get's it individually with `useShopSession` hook. Is that right?!

**Comment by robinandeer** [comment]
> So now I think I got the full picture: we get the `shopSession` high in the tree in the page component, and them just pass it down via prop so other containers can do something with it instead of each container get's it individually with `useShopSession` hook. Is that right?!

Yes pretty much like that. Mostly to avoid having to handle loading states in every component.

With server components we would do it differently. Then we would fetch shop session for every component that needs it 🙂

**Comment by robinandeer** [comment]
### Merge Activity

* **Aug 25, 10:52 AM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3037).

**Pull request merged**
