### PR TITLE
Refactor CartEntryItem helper components

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Refactor CartEntryItem helpers to only accept props they actually use.

## Justify why they are needed

Make it possible to reuse them instead. Also avoid making them tightly coupled to the API.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2738** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2738" target="_blank">Graphite</a>  👈
    * **PR #2739** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2739" target="_blank">Graphite</a> 
      * **PR #2740** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2740" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2738?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
Nice refactor!

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2738).

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2738).

**Pull request merged**
