### PR TITLE
Add vertical alignment settings to HeroBlock

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Add vertical alignment settings to HeroBlock 

## Justify why they are needed
More layout settings

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2503** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2503" target="_blank">Graphite</a> 
    * **PR #2505** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2505" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2505?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]

**Comment by gustaveen** [comment]
@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2505).

**Comment by gustaveen** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2505) rebased this pull request as part of a merge.

**Comment by gustaveen** [comment]
@gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2505).

**Pull request merged**
