### PR TITLE
GEN-1143 | TrialExtensionBlock: draft implementation

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Implement draft of car trial extension block (car dealership)

- Narrow type in `ProductItemContractContainer`

## Justify why they are needed

- This is still a WIP, let's see if it makes sense to merge now

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3234** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3234" target="_blank">Graphite</a> 
    * **PR #3235** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3235" target="_blank">Graphite</a> 
      * **PR #3236** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3236" target="_blank">Graphite</a> 
        * **PR #3237** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3237" target="_blank">Graphite</a> 
          * **PR #3238** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3238" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3238?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3234** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3234" target="_blank">Graphite</a> 
    * **PR #3235** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3235" target="_blank">Graphite</a> 
      * **PR #3236** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3236" target="_blank">Graphite</a> 
        * **PR #3237** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3237" target="_blank">Graphite</a> 
          * **PR #3238** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3238" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3238?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Looks solid :)
I'm ok with merging this and iterating over it along the way we develop the feature.

**Comment by robinandeer** [comment]
### Merge Activity

* **Sep 20, 2:01 PM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3238).

**Pull request merged**
