### PR TITLE
Tweak design of Checkout Page

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Slightly update design of Checkout page to match design.

Fix submit handler so it only fetches inputs that are in the form.

## Justify why they are needed

Currently discussing which data we are supposed to collect from users.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1107** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1107" target="_blank">Graphite</a> 
    * **PR #1108** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1108" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1108?utm_source=stack-comment).

**Review by amandaflod — APPROVED** [review]
👍

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1108?utm_source=stack-comment).


Job Reference: 6uA7pDLqloLLc4t1jKbk

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1108?utm_source=stack-comment).


Job Reference: wZHqFJrhO9sZ9NAO55PJ

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1108?utm_source=stack-comment).


Job Reference: IpPoxe4fQc1wU6Fa0wjx

**Pull request merged**
