### PR TITLE
Make `PriceLoader` a reusable component

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Extract `PriceLoader` from `PurchaseForm`

## Justify why they are needed

- We want to use it in the Widget

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3544** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3544?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3545** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3545?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3546** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3546?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3547** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3547?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3548** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3548?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3549** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3549?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
              * **PR #3550** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3550?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3551** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3551?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3549?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3544** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3544?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3545** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3545?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3546** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3546?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3547** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3547?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3548** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3548?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3549** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3549?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
              * **PR #3550** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3550?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3551** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3551?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3549?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Added via Giphy

**Review by gustaveen — APPROVED** [review]
👌

**Pull request merged**
