### PR TITLE
Use Apollo Client in CartService

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Replace graphql SDK with Apollo Client server side.

## Justify why they are needed

I want to remove graphql SDK so we just end up with one way to query graphql.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #399** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/399" target="_blank">Graphite</a> 
    * **PR #400** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/400" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/400?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Well done 🧹 
Just as a refreshment, why do we have `graphqlSDK` again?

**Review by alebedev — APPROVED** [review]
Looks great!  Just 2 usages of graphql/sdk remaining in the project.  Are we planning to remove those too?

**Review by robinandeer — COMMENTED** [review]
@guilhermespopolin / @alebedev Yes, I'm removing the other stuff in upcoming PRs.

I added it some time ago since we got better type safety and less boilerplate when calling GraphQL from the server. But I'm realizing it adds more hassle to maintain two ways to call the API :P

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/400?utm_source=stack-comment).


Job Reference: HDRvpmcM7CIUcsAihL9P

**Pull request merged**
