### PR TITLE
Configure Datadog service name for RUM (client)

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Add `NEXT_PUBLIC_DATADOG_SERVICE_NAME` env var that will be exposed to the JS client to set Datadog service name.

## Justify why they are needed

This is required for Datadog tracing.

I decided to keep `DD_SERVICE` since it's the official env var for this setting.
Perhaps Datadog on the server will read this as well...

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #647** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/647" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/647?utm_source=stack-comment).

**Review by simonauner — APPROVED** [review]
Nice fix, but weird that this stopped working, I'm quite sure it worked when I was implementing the server part 🤔 .

The BE logging will not read the env variable per se, but the `service` prop in the config is used.

**Review by alebedev — APPROVED** [review]
Looks good

**Review by robinandeer — COMMENTED** [review]
@simonauner yeah exactly, I guess the env var would only be a backup... perhaps we can remove it and just rely on the config :)

Don't think anything stopped working -- `DD_SERVICE` wasn't used before in the client I guess.

**Pull request merged**
