### PR TITLE
Support CMS-defined content on migration page

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Support pre-offers and post-offers CMS content on Manypets migration page

## Justify why they are needed

Should allow us to put custom content from CMS instead of hardcoding it

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2327** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2327" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2327?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
LGTM

**Comment by alebedev** [comment]
@alebedev queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2327).

**Comment by alebedev** [comment]
@alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2327).

**Pull request merged**
