### PR TITLE
Remove standalone switching assistant page

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Remove standalone switching assistant page

## Justify why they are needed

- The module has been moved to the confirmation page

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2530** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2530" target="_blank">Graphite</a> 
    * **PR #2531** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2531" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2531?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice cleanup

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2531).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2531) rebased this pull request as part of a merge.

**Pull request merged**
