### PR TITLE
GEN-1196 | Car dealership: show dialog when confirming price fails

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Car dealership: show error dialog with possible user error message when confirming price fails

## Justify why they are needed

- UX improvement

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3265** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3265" target="_blank">Graphite</a> 
    * **PR #3266** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3266" target="_blank">Graphite</a> 
      * **PR #3269** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3269" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3269?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
I remember we have a hook - `useErrorMessage` I think, that maybe might help with this?!

**Comment by robinandeer** [comment]
@guilhermespopolin yeah my bad, I'm gonna update it

**Comment by robinandeer** [comment]
### Merge Activity

* **Sep 26, 9:39 AM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3269).

**Pull request merged**
