### PR TITLE
Add fetch insurance success component

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add Fetch Insurance Success state component

## Justify why they are needed

- Should be displayed at the end of Insurely flow

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2538** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2538" target="_blank">Graphite</a>  👈
    * **PR #2539** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2539" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2538?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2538).

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2538).

**Pull request merged**
