### PR TITLE
GEN-1385 | Widget select product - integrate product metadata

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Integrate product metadata from API into the widget select product page

- Fetch and hydrate product metadata from API

## Justify why they are needed

- Next step will be to filter the products based on the CMS configuration

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3520** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3520" target="_blank">Graphite</a> 
    * **PR #3521** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3521" target="_blank">Graphite</a> 
      * **PR #3522** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3522" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3522?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]

**Review by alebedev — APPROVED** [review]

**Review by guilhermespopolin — APPROVED** [review]
Looking alive :)

**Review by gustaveen — APPROVED** [review]
👏

**Comment by robinandeer** [comment]
### Merge activity

* **Nov 8, 10:08 AM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3522).

**Pull request merged**
