### PR TITLE
Create payments page and refactor

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Feel free to refactor how we distribute the data, didn't touch it now @alebedev 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3339** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3339" target="_blank">Graphite</a> 
    * **PR #3340** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3340" target="_blank">Graphite</a> 
      * **PR #3341** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3341" target="_blank">Graphite</a> 
        * **PR #3342** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3342" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3342?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good!  Will need some changes after we merge all the branches to bring hooks and translations

**Review by alebedev — APPROVED** [review]
Looks good!

**Comment by gustaveen** [comment]
### Merge Activity

* **Oct 5, 5:09 AM**: @gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3342).

**Pull request merged**
