### PR TITLE
GEN-764 | Catch errors in debug dialog shortcut effect

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Avoid error when checking shortcut for debug dialog

Source: https://datadoghq.eu/rum/error-tracking?query=@application.id:d86e86d8-8d9a-4b00-a2cb-10b8d7671fa2&issueId=00c44958-2246-11ee-83d3-da7ad0900005&from_ts=1689590266557&to_ts=1689593866557&live=true

## Justify why they are needed

- We don't want uncaught exceptions

- I decided to log an error if the code would still contain some issues

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2795** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2795" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2795?utm_source=stack-comment).

**Review by alebedev — COMMENTED** [review]
Do you think we need it?  Datadog should log unhandled errors as it is.  Are we expecting anything else than programming errors here?

**Comment by robinandeer** [comment]
> Do you think we need it?  Datadog should log unhandled errors as it is.  Are we expecting anything else than programming errors here?

I think we are expecting some browsers to not support the APIs we are using

The reason to log it to Datadog is to add the context of which type of event we are dealing with etc.

**Review by alebedev — APPROVED** [review]
Discussed in person, looks good

**Pull request merged**
