### PR TITLE
Add form template for SE apartment

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Add form template for SE apartment

Show loading UI while confirming price intent.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #592** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/592" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/592?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
LGTM! 🙌

**Review by alebedev — APPROVED** [review]
Nice!

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/592?utm_source=stack-comment).


Job Reference: qsfJXT0umdPp4CZsc92J

**Pull request merged**
