### PR TITLE
GEN-821: refact(CartItem): consolidate CantEntry type 

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## Describe your changes

* Updates `CartItem` API

## Justify why they are needed

Simplify how `CartItem` get it's props.

### CODE REVIEW

**Comment by guilhermespopolin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2859** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2859" target="_blank">Graphite</a> 
    * **PR #2873** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2873" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2873?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
I think it looks great! Sorry for no more specific feedback hehe

**Comment by guilhermespopolin** [comment]
@guilhermespopolin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2873).

**Comment by guilhermespopolin** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2873) rebased this pull request as part of a merge.

**Pull request merged**
