### PR TITLE
Add edit button to `CartEntryItem`

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Allow users to edit cart items by pressing a button in the cart

## Justify why they are needed

- Makes it easier to edit items in the cart

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

[GRW-2451]: https://hedvig.atlassian.net/browse/GRW-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2190** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2190" target="_blank">Graphite</a> 
    * **PR #2191** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2191" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2191?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2191).

**Comment by robinandeer** [comment]
@robinandeer queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2191).

**Pull request merged**
