### PR TITLE
Remove unused export from UI kit

### PR DESCRIPTION
**Pull request by robinandeer**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2680** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2680" target="_blank">Graphite</a> 
    * **PR #2681** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2681" target="_blank">Graphite</a> 
      * **PR #2682** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2682" target="_blank">Graphite</a> 
        * **PR #2683** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2683" target="_blank">Graphite</a> 
          * **PR #2686** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2686" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2686?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2686).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2686) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2686).

**Pull request merged**
