### PR TITLE
Rename pet-migration -> manypets-migration

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

New migration URL as agreed in project channel

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2275** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2275" target="_blank">Graphite</a> 
    * **PR #2277** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2277" target="_blank">Graphite</a>  👈
      * **PR #2278** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2278" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2277?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Looks good, just rebase before merge!

**Comment by alebedev** [comment]
@alebedev queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2277).

**Comment by alebedev** [comment]
@alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2277).

**Pull request merged**
