### PR TITLE
Make ProductPageContext smaller, we did not use most of the data there

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Make value of ProductPageContext match actual usage

## Justify why they are needed

I'll see if we can/should convert this to jotai atoms.  Removing dead code first to make it easier

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3990?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#3990** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3990?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3988** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3988?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3987** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3987?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3990?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Nice. I've missed this 'trustpilot' thing when I did my cleanup 😅

**Comment by alebedev** [comment]
Not only trustpilot, we had like 10 unused props, some with quite big payload

**Comment by alebedev** [comment]
### Merge activity

* **Feb 29, 5:07 AM EST**: [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3990) rebased this pull request after merging its parent, because this pull request is set to merge when ready.
* **Feb 29, 5:11 AM EST**: @alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3990).

**Pull request merged**
