### PR TITLE
Translate SE apartment forms

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Translate different parts of the SE apartment forms.

Update translation hook to get keys from "purchase-form" namespace.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

[GRW-1877]: https://hedvig.atlassian.net/browse/GRW-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #985** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/985" target="_blank">Graphite</a> 
    * **PR #987** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/987" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/987?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/987?utm_source=stack-comment).


Job Reference: NyqCkgg7tzcsRE7hLfXP

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/987?utm_source=stack-comment).


Job Reference: JZRQe0PpwZMxwAQsDiRu

**Pull request merged**
