### PR TITLE
Update video controls animation and position

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Update the mute state and when it animates. Also moved the sound controls next to the play button

- Muted (first load): soundbars animate once and then stops
- Muted or paused: static soundbars
- Unmuted: looping animating soundbars 

## Justify why they are needed
Talked with William regarding the sound controls and we thought the mute state was a bit unclear currently.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3040** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3040" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3040?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Looks good :)



We do seem to have some artifacts in the SVG though... I think it might not quite line up to the pixel grid the same way that the pause button does

**Comment by gustaveen** [comment]
> Looks good :)
> 
> 
> 
> We do seem to have some artifacts in the SVG though... I think it might not quite line up to the pixel grid the same way that the pause button does

Indeed, looks a bit off especially now when they are side to side. I'll ask William to have a look 👍

**Comment by gustaveen** [comment]
@gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3040).

**Pull request merged**
