### PR TITLE
[GEN-555] Group ManyPets into a feature folder

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Group related ManyPets modules into a single feature folder

## Justify why they are needed

- I tried to keep this PR pretty simple so there are a lot of things still scattered around

- We can build on this initial PR and move more logic out of Next.js pages and into the feature folder

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2551** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2551" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2551?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Review by gustaveen — APPROVED** [review]
Awesome! 🙌

**Review by guilhermespopolin — APPROVED** [review]
Well done :)

**Pull request merged**
