### PR TITLE
Remove market-web rewrites and fallback url feature flag

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Remove market-web rewrites and fallback url feature flag

## Justify why they are needed
Shut down market-web

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3491** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3491" target="_blank">Graphite</a> 
    * **PR #3492** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3492" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3492?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!   I remember Robin posted blocking mode for staticPaths in CMS pages - are there other similar things that weren't possible before but we want to do now?

**Comment by gustaveen** [comment]
> Nice! I remember Robin posted blocking mode for staticPaths in CMS pages - are there other similar things that weren't possible before but we want to do now?

Good question, not that I can think of top of mind but let's see 🙌 @alebedev

**Comment by gustaveen** [comment]
### Merge activity

* **Oct 26, 10:04 AM**: @gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3492).

**Pull request merged**
