### PR TITLE
Update cart add mutation

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Update cart add mutation

Rename line item -> priced (product) variant.

Update mocks.

## Justify why they are needed

Update GraphQL definitions to avoid using deprecated mutation.

Will continue to update mock setup in a separate PR.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #568** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/568" target="_blank">Graphite</a> 
    * **PR #569** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/569" target="_blank">Graphite</a> 
      * **PR #570** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/570" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/570?utm_source=stack-comment).

**Review by simonauner — APPROVED** [review]
gif

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/570?utm_source=stack-comment).


Job Reference: veHzKaJUkgSYFeEBcmqY

**Review by gustaveen — APPROVED** [review]
🛒 🙌

**Pull request merged**
