### PR TITLE
ShopBreakdown: implement on `ManyPetsMigrationPage`

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Implement shop breakdown on many pets migration page

- Add comment about why we don't show discount

## Justify why they are needed

- Last place we are using the old components!

- ~I can't preview this locally so let's verify in the preview app~ Testing in staging 🙂 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3035** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3035" target="_blank">Graphite</a> 
    * **PR #3036** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3036" target="_blank">Graphite</a> 
      * **PR #3037** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3037" target="_blank">Graphite</a> 
        * **PR #3043** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3043" target="_blank">Graphite</a> 
          * **PR #3044** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3044" target="_blank">Graphite</a> 
            * **PR #3046** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3046" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3046?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Review by guilhermespopolin — APPROVED** [review]
Nice

**Comment by robinandeer** [comment]
### Merge Activity

* **Aug 28, 10:58 AM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3046).

**Pull request merged**
