### PR TITLE
Port meta alternate fixes to app router

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Fix alternate metadata for app router
- Remove trailing slashes
- Replace URL for /se

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Review by gustaveen — APPROVED** [review]
👌

**Review by Youakeem — APPROVED** [review]
It definitely reads better but l am missing logic changes aside from normalizing the URLs.

**Comment by alebedev** [comment]
No logic changes in actual behavior, but the comment in old version was misleading about intended behavior when there was only one version

**Comment by alebedev** [comment]
### Merge activity

* **May 31, 6:58 AM EDT**: @alebedev started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4327).

**Pull request merged**
