### PR TITLE
Add `TotalAmount` component

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add `TotalAmount` component based on Figma design (part of Shop Breakdown)

## Justify why they are needed

- Will be used inside new Shop Breakdown component (to come)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2936** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2936" target="_blank">Graphite</a> 
    * **PR #2939** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2939" target="_blank">Graphite</a> 
      * **PR #2940** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2940" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2940?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2940).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2940) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2940).

**Pull request merged**
