### PR TITLE
GEN-1515 | Fix tooltip on mobile

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Open Tooltip on click

## Justify why they are needed

- Fix issue on mobile where the tooltip would not open when tapping on the icon

- Reference: https://github.com/radix-ui/primitives/issues/955#issuecomment-1698976935

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3667** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3668** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3668?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3669** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3669?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3670** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3670?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3671** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3671?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3672** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3672?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3672?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3667** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3668** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3668?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3669** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3669?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3670** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3670?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3671** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3671?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3672** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3672?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3672?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
Awesome, good find!

**Comment by robinandeer** [comment]
### Merge activity

* **Nov 30, 9:44 AM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3672).

**Pull request merged**
