### PR TITLE
Update implementation to match nested schema

### PR DESCRIPTION
**Pull request by robinandeer**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #321** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/321" target="_blank">Graphite</a> 
    * **PR #323** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/323" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/323?utm_source=stack-comment).

**Review by dendoesit — APPROVED** [review]
👍

**Review by guilhermespopolin — APPROVED** [review]
🚀

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/323?utm_source=stack-comment).


Job Reference: gjKpviQE95hVRnCGYPiY

**Pull request merged**
