### PR TITLE
Group all generated graphql files in a single folder

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Group all generated files in a single folder: `src/services/graphql/`

## Justify why they are needed

- Make it easier to exclude all those files from eslint and git

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #3733** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3733?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3734** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3734?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3734?utm_source=stack-comment).

**Review by alebedev — COMMENTED** [review]
Did you mean to commit generate 5.5KLOC file?  Looks good otherwise

**Review by alebedev — APPROVED** [review]

**Review by gustaveen — APPROVED** [review]
👍

**Comment by robinandeer** [comment]
### Merge activity

* **Dec 15, 11:31 AM**: @@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3734).

**Pull request merged**
