### PR TITLE
Add additional BankSignering actions

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add a few more DD actions to better track BankSignering feature

## Justify why they are needed

- Be able to setup a proper funnel in DD

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2927** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2927" target="_blank">Graphite</a> 
    * **PR #2944** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2944" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2944?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good, let's merge

**Comment by alebedev** [comment]
@alebedev started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2944).

**Comment by alebedev** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2944) rebased this pull request as part of a merge.

**Comment by alebedev** [comment]
@alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2944).

**Pull request merged**
