### PR TITLE
Quick and dirty migration offers display and sign

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Show Pet migration offers and allow to sign them

## Justify why they are needed

First working prototype of Leif signing

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2265** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2265" target="_blank">Graphite</a> 
    * **PR #2266** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2266" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2266?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]

**Comment by alebedev** [comment]
@alebedev queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2266).

**Comment by alebedev** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2266) rebased this pull request as part of a merge.

**Comment by alebedev** [comment]
@alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2266).

**Pull request merged**
