### PR TITLE
Update README with installations steps for VS Code SDK

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Update README with installations steps for VS Code SDK

Holler if you think there's a better way to set this up :) 

## Justify why they are needed
Needed to make VS Code work with Yarn PnP

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3393** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3393" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3393?utm_source=stack-comment).

**Review by robinandeer — COMMENTED** [review]
Ughhhh so many files 😬

Seems like we could also ignore these files but then users need to initialize it after doing a new clone of the repo

**Review by robinandeer — APPROVED** [review]
Awesome!

Can you also update the `.gitignore` to exclude `.yarn/sdks` folder :)

**Review by guilhermespopolin — APPROVED** [review]

**Comment by gustaveen** [comment]
> Maybe we should recommend `""arcanis.vscode-zipfs""` extension as well:
> 
> ```js
> // .vscode/extensions.json
> 
> {
>   "recommendations": [
>     "dbaeumer.vscode-eslint",
>     "esbenp.prettier-vscode",
>     "unifiedjs.vscode-mdx",
>     "apollographql.vscode-apollo",
>     "arcanis.vscode-zipfs"
>   ]
> }
> ```

I'm thinking it's only needed for downloading once so though it might be overhead to add it 🙃

**Comment by gustaveen** [comment]
### Merge Activity

* **Oct 11, 5:25 AM**: @gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3393).

**Pull request merged**
