### PR TITLE
Define theme box shadows

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Define three pre-defined box shadows in the theme object

    - default box shadow used on buttons etc.
    - focus styles (one for light and one for dark elements)

- Remove unused "Tabs" component

## Justify why they are needed

- Started seeing this same pattern all over the code base so probably time to add it to the theme.

- I used the new-ish color format `rgb(2 2 2 / 20%)` because it's easier to read

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2825** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2825" target="_blank">Graphite</a> 
    * **PR #2826** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2826" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2826?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Very nice!

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2826).

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2826).

**Pull request merged**
