### PR TITLE
Widget | Report 'delete_from_cart' when removing cart item

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- See title.

## Justify why they are needed

- Widget tracking

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3641** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3641?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3642** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3642?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3643** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3643?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3644** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3645** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3645?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3646** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3646?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3647** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3647?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3648** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3648?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3651** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3651?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                    * **PR #3652** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3652?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3651?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3641** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3641?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3642** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3642?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3643** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3643?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3644** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3645** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3645?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3646** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3646?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3647** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3647?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3648** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3648?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3651** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3651?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                    * **PR #3652** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3652?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3651?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3641** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3641?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3642** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3642?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3643** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3643?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3644** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3644?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3645** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3645?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3646** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3646?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3647** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3647?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3648** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3648?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3651** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3651?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                    * **PR #3652** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3652?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3651?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Pull request merged**
