### PR TITLE
Only initialize Storyblok bridge when inside iframe

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Prevent "You are not in Draft Mode or in the Visual Editor" warning by only enabling Storyblok bridge in iframe

## Justify why they are needed

One step closer to zero warnings

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1328** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1328" target="_blank">Graphite</a> 
    * **PR #1329** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1329" target="_blank">Graphite</a> 
      * **PR #1330** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1330" target="_blank">Graphite</a> 
        * **PR #1331** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1331" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1331?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Nice with the comment also 🍡

**Review by guilhermespopolin — APPROVED** [review]

**Review by gustaveen — APPROVED** [review]
Great! 🙌

**Comment by alebedev** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: gB2FZ4kHDcMJ8rHykAQX.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1331)

**Pull request merged**
