### PR TITLE
Add visual component for sticky price footer

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Group product page components in Storybook.

## Justify why they are needed

Make it clear in Storybook which components should be used only on certain pages.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

[GRW-1301]: https://hedvig.atlassian.net/browse/GRW-1301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #343** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/343" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/343?utm_source=stack-comment).

**Review by dendoesit — APPROVED** [review]
great.

**Review by guilhermespopolin — APPROVED** [review]
:)

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/343?utm_source=stack-comment).


Job Reference: dHviibmih86u4jWvOczB

**Pull request merged**
