### PR TITLE
Group together product data related utilities

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Group all product data related utilities in one place

## Justify why they are needed

- I will build on this in the following PRs. The idea is to extract product data from the "product page context" so we can reuse it in other places, like in the widget.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3628** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3628?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3628?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Nice. So ultimately we will have a `ProductDataContext`? I asking because right now we have a `components/ProductData` folder that doesn't include any "component" related code...

**Comment by robinandeer** [comment]
> Nice. So ultimately we will have a `ProductDataContext`? I asking because right now we have a `components/ProductData` folder that doesn't include any "component" related code...
> 
> 

Yes exactly! That is the plan

**Comment by robinandeer** [comment]
### Merge activity

* **Nov 23, 4:45 PM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3628).

**Pull request merged**
