### PR TITLE
Remove price calculator title

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

See title.

## Justify why they are needed

Design update.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #873** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/873" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/873?utm_source=stack-comment).

**Review by amandaflod — APPROVED** [review]
👍

**Review by gustaveen — APPROVED** [review]
👍 Did you remove it Storyblok as well?

**Comment by alebedev** [comment]
I checked - Storyblok field is gone.  Going to merge this to move forward with demo preparation

**Pull request merged**
