### PR TITLE
GEN-736 | Share link to cart from debug dialog

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Implement debug dialog on cart page

- Add section for sharing a link to the cart (and session)

- Remove global debug dialog instance in favor of page specific instances

- Refactor debug dialog to be more composable

- Add session link helper to `PageLink`

## Justify why they are needed

- We want to help inbound/outbound support teams to generate offers and share link to the cart

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2758** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2758" target="_blank">Graphite</a> 
    * **PR #2765** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2765" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2765?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Nice, nice

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2765).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2765) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2765).

**Pull request merged**
