### PR TITLE
Update start date mutation

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Update start date mutation

Change line item id -> priced variant id.

## Justify why they are needed

Match updated schema, switch from deprecated endpoints.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #568** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/568" target="_blank">Graphite</a> 
    * **PR #569** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/569" target="_blank">Graphite</a> 
      * **PR #570** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/570" target="_blank">Graphite</a> 
        * **PR #571** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/571" target="_blank">Graphite</a> 
          * **PR #572** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/572" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/572?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #568** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/568" target="_blank">Graphite</a> 
    * **PR #569** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/569" target="_blank">Graphite</a> 
      * **PR #570** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/570" target="_blank">Graphite</a> 
        * **PR #571** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/571" target="_blank">Graphite</a> 
          * **PR #572** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/572" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/572?utm_source=stack-comment).

**Review by simonauner — APPROVED** [review]
gif

**Review by KarnellSchultz — APPROVED** [review]

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/572?utm_source=stack-comment).


Job Reference: veHzKaJUkgSYFeEBcmqY

**Review by guilhermespopolin — APPROVED** [review]

**Pull request merged**
