### PR TITLE
GEN-667 - Add mute/unmute button to videos

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Add toggle sound button to videos

TODO: add correct icon

https://github.com/HedvigInsurance/racoon/assets/6661511/3b9c0423-d3b7-43ee-8c2a-978280f13b5a

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2759** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2759" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2759?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Looks good :)

**Comment by gustaveen** [comment]
@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2759).

**Comment by gustaveen** [comment]
@gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2759).

**Pull request merged**
