### PR TITLE
Widget | Include price intent ID in sign page URL

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- include price intent ID in the URL for the sign page (widget)

## Justify why they are needed

- we need this information to be able to navigate back to the price caluclator step

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3583** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3584** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3584?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3586** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3587?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3591** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3591?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3592** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3592?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3593** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3593?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3594** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3594?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3595** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #3596** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3596?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #3597** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #3598** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #3599** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #3600** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #3601** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #3602** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3602?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                  * **PR #3603** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3603?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                    * **PR #3604** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3604?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                                      * **PR #3605** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3605?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3604?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3583** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3584** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3584?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3586** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3587?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3591** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3591?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3592** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3592?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3593** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3593?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3594** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3594?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3595** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #3596** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3596?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #3597** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #3598** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #3599** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #3600** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #3601** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #3602** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3602?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                  * **PR #3603** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3603?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                    * **PR #3604** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3604?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                                      * **PR #3605** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3605?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3604?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3583** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3584** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3584?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3586** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3587** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3587?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3591** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3591?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3592** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3592?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #3593** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3593?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #3594** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3594?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #3595** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #3596** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3596?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #3597** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #3598** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #3599** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #3600** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3600?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #3601** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #3602** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3602?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                  * **PR #3603** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3603?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                    * **PR #3604** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3604?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                                      * **PR #3605** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3605?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3604?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Comment by robinandeer** [comment]
### Merge activity

* **Nov 21, 5:02 PM**: @robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3604).

**Pull request merged**
