### PR TITLE
Integrate product data from API on cart page

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Integrate product data from API on Cart and Checkout pages.

Remove unused `OfferInventoryItem` component.

Update Storybook stories.

## Justify why they are needed

It's not 100% clear when to use which display name for products and offers. Let's review and discuss with designers.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1107** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1107" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1107?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1107?utm_source=stack-comment).


Job Reference: 6uA7pDLqloLLc4t1jKbk

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1107?utm_source=stack-comment).


Job Reference: wZHqFJrhO9sZ9NAO55PJ

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1107?utm_source=stack-comment).


Job Reference: IpPoxe4fQc1wU6Fa0wjx

**Pull request merged**
