### PR TITLE
Tech: Use input theme component tokens

### PR DESCRIPTION
**Pull request by Youakeem**
## Describe your changes
Use component specific theme tokens instead of standalone variables.

## Checklist before requesting a review

- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Youakeem** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4270?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4270** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4270?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4266** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4266?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Youakeem and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by guilhermespopolin — APPROVED** [review]
Nice work with this 🚀 
Definitely an improvement

**Comment by Youakeem** [comment]
> Nice work with this 🚀 
> Definitely an improvement
> 
> 

Thank you, man! 🙏

**Comment by Youakeem** [comment]
### Merge activity

* **May 15, 10:11 AM EDT**: @Youakeem started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4270).

**Pull request closed without merging**
