### PR TITLE
[GEN-412] Add Article Category List component

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Build article category list component

## Justify why they are needed

Will be used on blog page to list the links to individual categoy pages

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2462** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2462" target="_blank">Graphite</a> 
    * **PR #2466** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2466" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2466?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good!

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2466).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2466) rebased this pull request as part of a merge.

**Pull request merged**
