### PR TITLE
Update to fix layout on checkout contact details page

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Fix link back to review/start date screen on Checkout Contact Details page.

Tweak layout of same page to match the review/start date screen.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

[GRW-1569]: https://hedvig.atlassian.net/browse/GRW-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #610** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/610" target="_blank">Graphite</a> 
    * **PR #613** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/613" target="_blank">Graphite</a> 
      * **PR #620** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/620" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/620?utm_source=stack-comment).

**Review by amandaflod — APPROVED** [review]
Nice! 💅

**Comment by simonauner** [comment]
a11y police here: There's no `focus-visible` styling on these kind of links which makes it impossible to see if they're active with keyboard navigation only. Maybe out of scope for this PR but I feel I need to point it out 👮

**Review by guilhermespopolin — APPROVED** [review]
Looks good. Agree with Simmon about the lack of a focus ring.

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/620?utm_source=stack-comment).


Job Reference: otDkpy8tB4rmLMp8y6We

**Pull request merged**
