### PR TITLE
Delete unused VideioListBlock

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Delete unused VideioListBlock (it's replaced with MediaListBlock)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3799?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #3798** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3798?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3799** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3799?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3799?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
great!!

**Review by guilhermespopolin — APPROVED** [review]

**Comment by gustaveen** [comment]
### Merge activity

* **Jan 3, 9:00 AM**: [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3799) rebased this pull request as part of a merge.

**Pull request merged**
