### PR TITLE
ShopBreakdown: implement product item container in retargeting block

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Implement product item container in retargeting block

- Move product item container to product item folder to indicate that it is reusable

- Make container accept children instead of rendering predefined action buttons

## Justify why they are needed

- I will continue implementing and seeing if this is the right abstractions

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3010** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010" target="_blank">Graphite</a> 
    * **PR #3011** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3011" target="_blank">Graphite</a> 
      * **PR #3012** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3012" target="_blank">Graphite</a> 
        * **PR #3013** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013" target="_blank">Graphite</a> 
          * **PR #3015** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3015" target="_blank">Graphite</a> 
            * **PR #3017** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3017" target="_blank">Graphite</a> 
              * **PR #3018** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3018" target="_blank">Graphite</a> 
                * **PR #3019** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3019" target="_blank">Graphite</a> 
                  * **PR #3021** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3021" target="_blank">Graphite</a> 
                    * **PR #3022** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3022" target="_blank">Graphite</a> 
                      * **PR #3023** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3023" target="_blank">Graphite</a> 
                        * **PR #3024** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3024" target="_blank">Graphite</a> 
                          * **PR #3027** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3027" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3027?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3010** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3010" target="_blank">Graphite</a> 
    * **PR #3011** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3011" target="_blank">Graphite</a> 
      * **PR #3012** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3012" target="_blank">Graphite</a> 
        * **PR #3013** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3013" target="_blank">Graphite</a> 
          * **PR #3015** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3015" target="_blank">Graphite</a> 
            * **PR #3017** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3017" target="_blank">Graphite</a> 
              * **PR #3018** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3018" target="_blank">Graphite</a> 
                * **PR #3019** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3019" target="_blank">Graphite</a> 
                  * **PR #3021** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3021" target="_blank">Graphite</a> 
                    * **PR #3022** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3022" target="_blank">Graphite</a> 
                      * **PR #3023** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3023" target="_blank">Graphite</a> 
                        * **PR #3024** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3024" target="_blank">Graphite</a> 
                          * **PR #3027** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3027" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3027?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Review by guilhermespopolin — APPROVED** [review]
Nice, nice

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3027) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3027).

**Pull request merged**
