### PR TITLE
Fix campaign code middleware bug

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Remove async keyword from sync function.

Add log message.

## Justify why they are needed

Bug.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #418** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/418" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/418?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
There's a way to catch things like this with typescript.  If you declare return type explicitly it'll act as an assertion for what you're actually returning.  For example, original bug is caught
by following declaration
```
export function middleware(request: NextRequest): NextResponse {
  ...
}

**Review by gustaveen — APPROVED** [review]
🕵️‍♂️

**Review by robinandeer — COMMENTED** [review]
@alebedev very true! I will add that, thx :D

**Pull request merged**
