### PR TITLE
GEN-1528 / Add QuickAdd accident USPs and make buttons full width

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
See title

Screenshot 2023-12-12 at 15 12 12

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3715** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3715?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3716** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3716?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3717** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3717?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3723** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3723?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3726** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3726?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3727** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3727?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3727?utm_source=stack-comment).

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3715** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3715?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3716** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3716?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3717** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3717?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3723** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3723?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #3726** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3726?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #3727** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3727?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3727?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
USP!

**Comment by gustaveen** [comment]
### Merge activity

* **Dec 14, 4:58 AM**: @@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3727).

**Pull request merged**
