### PR TITLE
Use manypets-specific query for migration page

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Subj

## Justify why they are needed

- Stop relying on deprecated shopSession.priceIntents
- Allows to send backend analytics events automatically when migration page is opened

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2282** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2282" target="_blank">Graphite</a> 
    * **PR #2283** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2283" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2283?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
👍

**Comment by alebedev** [comment]
@alebedev queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2283).

**Comment by alebedev** [comment]
@alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2283).

**Pull request merged**
