### PR TITLE
tech: export Card component from UI

### PR DESCRIPTION
**Pull request by Youakeem**
## Describe your changes
- Export the card component from the `ui` package
- Fix a `z-index` issue with the Card aside

## Justify why they are needed
Enable using `Card` in the `store` app

## Checklist before requesting a review

- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Youakeem** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4710?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4710** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4710?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4709** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4709?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4708** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4707** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4706** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4705** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4704** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4703** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4703?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Youakeem and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alebedev — APPROVED** [review]
Probably not worth a PR, you can squash it with one of previous PRs with Graphite CLI

**Review by guilhermespopolin — APPROVED** [review]

**Comment by Youakeem** [comment]
### Merge activity

* **Sep 19, 3:16 AM EDT**: @Youakeem started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4710).

**Pull request merged**
