### PR TITLE
Add resume shop session form to debug dialog

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add option to resume a shop session from debug dialog

## Justify why they are needed

Pretty common action

Styles are a bit off but I address that in the next PR

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2798** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2798" target="_blank">Graphite</a> 
    * **PR #2801** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2801" target="_blank">Graphite</a>  👈
      * **PR #2802** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2802" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2801?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2801).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2801) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2801).

**Pull request merged**
