### PR TITLE
Upgrade from deprecated ComponentMeta, ComponentStory types in @storybook/react

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Replace deprecated StorybookMeta, StorybookStory types with recommneded Meta and StoryFn.  All changes are very similar

## Justify why they are needed

Fix deprecations

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1994** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1994" target="_blank">Graphite</a> 
    * **PR #1996** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1996" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1996?utm_source=stack-comment).

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1994** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1994" target="_blank">Graphite</a> 
    * **PR #1996** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1996" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1996?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Damn but looks pretty straight forward

**Comment by alebedev** [comment]
@alebedev queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1996).

**Pull request merged**
