### PR TITLE
Only show pure breeds in mixed breed picker

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Show pure breeds in mixed breed picker.

## Justify why they are needed

We should only show named mixed breeds in the top level selector.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2059** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2059" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2059?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
👍

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2059).

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2059).

**Pull request merged**
