### PR TITLE
Trial debugger | redirect to URL from API

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Use the URL from the API to perform a redirect and kick off the extension widget flow

## Justify why they are needed

- Less copy pasting

- Requires API to be updated first

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3722** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3722?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3722?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Review by gustaveen — APPROVED** [review]
Neat! 👌

**Review by guilhermespopolin — APPROVED** [review]
Nice

"Less copy and paste"

**Pull request merged**
