### PR TITLE
Update personal number field to match design

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Update `PersonalNumberField` to match design in Figma.

Animate background to flash green on every keystroke.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #972** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/972" target="_blank">Graphite</a> 
    * **PR #973** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/973" target="_blank">Graphite</a> 
      * **PR #974** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/974" target="_blank">Graphite</a> 
        * **PR #975** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/975" target="_blank">Graphite</a> 
          * **PR #976** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/976" target="_blank">Graphite</a> 
            * **PR #978** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/978" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/978?utm_source=stack-comment).

**Comment by gustaveen** [comment]
Crisp! 🤩

I thought it was about to turn green when the input was valid though? 
Screenshot 2022-12-01 at 15 52 02

**Review by KarnellSchultz — APPROVED** [review]
👍

**Review by robinandeer — COMMENTED** [review]
@gustaveen I will discuss with Zak what the latest is but this is as far as I understood :)

We don't want to do too much client-side validation

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/978?utm_source=stack-comment).


Job Reference: tnRk3yNxxdFZ5CMl5L4E

**Pull request merged**
