### PR TITLE
chore(eslint): enable non-nullable-type-assertion-style rule

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by guilhermespopolin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2916** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2916" target="_blank">Graphite</a> 
    * **PR #2917** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2917" target="_blank">Graphite</a> 
      * **PR #2918** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2918" target="_blank">Graphite</a> 
        * **PR #2919** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2919" target="_blank">Graphite</a> 
          * **PR #2920** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2920" target="_blank">Graphite</a> 
            * **PR #2923** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2923" target="_blank">Graphite</a> 
              * **PR #2924** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2924" target="_blank">Graphite</a> 
                * **PR #2928** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2928" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2928?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]

**Review by alebedev — APPROVED** [review]

**Comment by guilhermespopolin** [comment]
@guilhermespopolin started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2928).

**Comment by guilhermespopolin** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2928) couldn't merge this pull request because a downstack PR #2916 failed to merge.

**Comment by guilhermespopolin** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2928) rebased this pull request as part of a merge.

**Comment by guilhermespopolin** [comment]
@guilhermespopolin merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2928).

**Pull request merged**
