### PR TITLE
Unify date formatting across blog

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Display dates in the same way across the blog pages

- Use localized dates; add new `dateFull` formatter utility

- Add "uppercase" prop to `Text` component

## Justify why they are needed

- Peter wants dates to be displayed in the same way across the blog pages

- Uppercasing text is a common design pattern

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2641** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2641" target="_blank">Graphite</a> 
    * **PR #2642** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2642" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2642?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2642).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2642) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2642).

**Pull request merged**
