### PR TITLE
Add animation to mute button

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Add animation to mute button
[Demo](https://hedvig-dot-com-git-feat-add-animated-mute-button-hedvig.vercel.app/se/forsakringar/olycksfallsforsakring)

https://github.com/HedvigInsurance/racoon/assets/6661511/88c860cb-0570-4536-97ee-8b988e6367db

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2759** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2759" target="_blank">Graphite</a> 
    * **PR #2769** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2769" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2769?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Nice :)

**Comment by gustaveen** [comment]
@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2769).

**Comment by gustaveen** [comment]
@gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2769).

**Pull request merged**
