### PR TITLE
Cancel Vercel deployments when newer commit exists on the same branch

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Cancel Vercel deployments when there's newer commit on the same branch

For some reason we didn't have it in our vercel.json - I think I just pasted some example from the docs without noticing this setting

## Justify why they are needed

- Prevent risk of older commit landing in production when merging stack of changes
- Reduce build queues on Vercel

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2282** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2282" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2282?utm_source=stack-comment).

**Review by gustaveen — APPROVED** [review]
Oh nice!

**Comment by alebedev** [comment]
@alebedev queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2282).

**Comment by alebedev** [comment]
@alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2282).

**Pull request merged**
