### PR TITLE
Fix small issues on debugger page

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Fix responsiveness issue on debugger page

Fix access to localstorage value in debugger page

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1385** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1385" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1385?utm_source=stack-comment).

**Review by amandaflod — APPROVED** [review]
Nice fixes! 🙌

**Review by alebedev — APPROVED** [review]
Looks good

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: kdCs7ZiimnMcFejGKps6.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1385)

**Pull request merged**
