### PR TITLE
GEN-747 | Share link to offer from debug dialog

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Implement page debug dialog on product pages

- Expose link to share an offer

## Justify why they are needed

- Needed for inbound/outbound sales team to share offers with customers

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2758** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2758" target="_blank">Graphite</a> 
    * **PR #2765** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2765" target="_blank">Graphite</a> 
      * **PR #2766** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2766" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2766?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2766).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2766) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2766).

**Pull request merged**
