### PR TITLE
GEN-1701 - tracking: removed offer_created and signed_customer events

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## Describe your changes

- Removed `offer_created` and `signed_customer` events

## Justify why they are needed

Requested by Sonny

### CODE REVIEW

**Comment by guilhermespopolin** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3853?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #3852** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3852?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3853** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3853?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3853?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Good cleanup!

**Review by gustaveen — APPROVED** [review]
🧹

**Comment by guilhermespopolin** [comment]
Gonna hold it for while until Sonny do some testing.

**Comment by guilhermespopolin** [comment]
Closing this one as Sonny requested doesn't know yet if we want that removed or not.

**Pull request closed without merging**
