### PR TITLE
Add userData to legacy analytics events

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Add hashed userData to legacy analytics events

## Justify why they are needed

- web-onboarding compatibility

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1350** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1350" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1350?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Looks good to me :)

**Comment by robinandeer** [comment]
@alebedev do we know if all browsers support these APIs?

**Comment by alebedev** [comment]
@robinandeer yes, works in all browsers we care about.  I'm glad IE11 is not among them :)

**Comment by alebedev** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: XEbG0stKuJhhhOJnnD01.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1350)

**Pull request merged**
