### PR TITLE
Sort deductibles based on monthly total

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Screenshot 2023-03-31 at 11 59 40

## Justify why they are needed
Logical order
## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2077** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2077" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2077?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
👏🏻 
Would be nice to get them sorted from BE though.

**Review by robinandeer — APPROVED** [review]
Looks good to me, reasonable logic even for client

Let's see if we should move to API later

**Comment by gustaveen** [comment]
Yes indeed, let's move it asap 🙌

**Pull request merged**
