### PR TITLE
Support rendering Market Web pages as fallback

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Support rendering Market Web pages as a fallback to those that are not yet found in the CMS.

## Justify why they are needed

Caveat #1: we need to use Market Web 404 page.

Caveat #2: we either need to setup custom rewrites for English locale or use the same format as Market Web.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2213** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2213" target="_blank">Graphite</a> 
    * **PR #2219** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2219" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2219?utm_source=stack-comment).

**Comment by gustaveen** [comment]
One thought to get around the caveat #1 we could target rewrites more specifically and have the 404 at new hedvig.com. Not sure how much content that we're missing, but we could remove rewrites incrementally. :) @robinandeer

**Review by alebedev — APPROVED** [review]
Nice!  Why do we have preview-related changes here, not based on main?

**Comment by robinandeer** [comment]
> Nice!  Why do we have preview-related changes here, not based on main?

fixed now!

**Review by guilhermespopolin — APPROVED** [review]
👌🏻

**Review by gustaveen — APPROVED** [review]
Let's merge! 🕺

**Pull request merged**
