### PR TITLE
Web Onboarding Redirects: add more home insurance sources

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Add all embark entry points for home insurance flows to be redirected to the new site

## Justify why they are needed

- Saw some traffic still in Datadog which was not being redirected to the new site

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2912** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2912" target="_blank">Graphite</a> 
    * **PR #2913** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2913" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2913?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

Odd that we got direct traffic to those pages

**Comment by robinandeer** [comment]
> Looks good
> 
> Odd that we got direct traffic to those pages

I actually think some users fall back to the landing page and then progress through the flow with client-side navigation.

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2913) rebased this pull request as part of a merge.

**Pull request merged**
