### PR TITLE
Refactor `CostSummary` to handle a single campaign

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Refactor `CostSummary` component to only handle single campaign

- Remove old references to `redeemedCampaigns` that are no longer needed

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2816** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2816" target="_blank">Graphite</a> 
    * **PR #2817** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2817" target="_blank">Graphite</a> 
      * **PR #2818** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2818" target="_blank">Graphite</a> 
        * **PR #2819** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2819" target="_blank">Graphite</a> 
          * **PR #2820** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2820" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2820?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Comment by robinandeer** [comment]
@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2820).

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2820) rebased this pull request as part of a merge.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2820).

**Pull request merged**
