### PR TITLE
Add Checkout breadcrumbs

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Update Checkout page with breadcrumbs from Figma.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1409** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1409" target="_blank">Graphite</a> 
    * **PR #1410** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1410" target="_blank">Graphite</a> 
      * **PR #1411** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1411" target="_blank">Graphite</a>  👈
        * **PR #1412** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1412" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1411?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!  We probably want same breadcrumbs on next steps too, right?  Not sure how to do this with payment connection at a reasonable cost

**Comment by robinandeer** [comment]
yeah but it's a pretty simple component

I will break it out into it's own when implementing the switching assistant page

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: VkfoBaXhK9maXJjhYuZx.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1411)

**Pull request merged**
