### PR TITLE
GEN-1612 | Fix tab navigation in `DayInput`

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

- Refactor `DayInput` to allow for keyboard use

- Toggle the expand-icon based on open state

## Justify why they are needed

- Better accessibility for keyboard users

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #3743** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3743?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3744** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3744?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3745** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3745?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3746** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3746?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3746?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #3743** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3743?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #3744** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3744?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #3745** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3745?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #3746** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3746?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3746?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Comment by robinandeer** [comment]
### Merge activity

* **Dec 15, 4:05 PM**: @@robinandeer started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3746).

**Pull request merged**
