### PR TITLE
Remove CartCollapsible and set open state on CartEntryItems

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Make CartEntryItems collapsible instead of the list. 

https://user-images.githubusercontent.com/6661511/233006493-fb985dd3-0590-451c-935f-0e836051cb0f.mov

## Justify why they are needed
When going directly to checkout, all items should be expanded

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2165** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2165" target="_blank">Graphite</a> 
    * **PR #2180** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2180" target="_blank">Graphite</a> 
      * **PR #2183** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2183" target="_blank">Graphite</a> 
        * **PR #2184** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2184" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2184?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Very nice!

**Comment by gustaveen** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2184) rebased this pull request as part of a merge.

**Comment by gustaveen** [comment]
@gustaveen queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2184).

**Pull request merged**
