### PR TITLE
Add close button to Dialog

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Add close button to PriceForm Modal

## Justify why they are needed
Being able to close the dialog

https://user-images.githubusercontent.com/6661511/199751626-774d1149-5e8b-47b4-b8df-4ea7b915d757.mov

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #799** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/799" target="_blank">Graphite</a> 
    * **PR #800** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/800" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/800?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Comment by gustaveen** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/800?utm_source=stack-comment).


Job Reference: T4J9Z5g30vvDfGFv0Uoy

**Review by KarnellSchultz — APPROVED** [review]
That which is open, shall now be closed. 

season-5-episode-20-gif-by-the-simpsons

**Pull request merged**
