### PR TITLE
fix(hydration-errors): make sure to import useTranslation from next-i18next

### PR DESCRIPTION
**Pull request by guilhermespopolin**
## Describe your changes

* Fix hydration errors on _Checkout_ page by changing from where `RemoveActionButton` gets `useTranslation` hook: `next-i18next` instead of `react-i18next`.

https://github.com/HedvigInsurance/racoon/assets/19200662/24f3ec28-ef2c-48d6-a445-e71b5938487c

Also took the liberty of updating it in other places of the codebase as well.
I could say (at lest personally) the major reason why that mistake insists on existing in your codebase is because intelisense only suggest auto importing `useTranslation` from `react-i18next`.  As a consequence I've added a eslint rule to help us to remember.

image

## Justify why they are needed

I didn't fully understand the issue but here's the context where it happens:

* `i18n` was not being initialised for `react-i18next` during build

In any case we should be using `useTranslation` hook from `next-i18next` so...

That hypothesis can be verified by adding the following to `RemoveActionButton`:

```
  const { t, ready } = useTranslation('cart')
  console.log('ready', ready)
  console.log('t', t('REMOVE_ENTRY_BUTTON'))
```

That would print `false` and `REMOVE_ENTRY_BUTTON` on the server but `true` and `Ta bort` on the client.

### CODE REVIEW

**Comment by guilhermespopolin** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #3858** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3858?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3858?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!  If this helps, can you looks into adding eslint rule forbidding direct imports from react-i18next?

**Review by gustaveen — APPROVED** [review]
Great find @guilhermespopolin 🥳
This is annoying yes, the auto import in VScode chooses `react-i18next` be default so a eslint rule would be nice 🙌

**Comment by guilhermespopolin** [comment]
> Nice! If this helps, can you looks into adding eslint rule forbidding direct imports from react-i18next?

Thanks for the suggestion. I've updated it by including a eslint config.

**Pull request merged**
