### PR TITLE
Add purchase form desktop fade in animation

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Add purchase form desktop fade in animation

https://github.com/HedvigInsurance/racoon/assets/6661511/1c0a6def-82c9-4d11-af99-923e4b084cb7

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2932** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2932" target="_blank">Graphite</a> 
    * **PR #2933** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2933" target="_blank">Graphite</a> 
      * **PR #2976** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2976" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2976?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
Nice :)

**Comment by gustaveen** [comment]
@gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2976).

**Comment by gustaveen** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2976) rebased this pull request as part of a merge.

**Comment by gustaveen** [comment]
@gustaveen merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2976).

**Pull request merged**
