### PR TITLE
Remove store-specific global styles

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

See title.

## Justify why they are needed

I don't know the reason why these were added.

Seems like we should keep all global styles in UI package ideally.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #497** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/497" target="_blank">Graphite</a> 
    * **PR #498** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/498" target="_blank">Graphite</a> 
      * **PR #499** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/499" target="_blank">Graphite</a> 
        * **PR #500** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/500" target="_blank">Graphite</a>  👈
          * **PR #501** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/501" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/500?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]

**Review by simonauner — APPROVED** [review]
YES! Kill it :D

**Review by guilhermespopolin — APPROVED** [review]
🗑️

**Comment by robinandeer** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/500?utm_source=stack-comment).


Job Reference: XGUpR1XoyR8aWNZag2G6

**Pull request merged**
