### PR TITLE
tech: [GEN-2609] Directly access shopSession in cart entries

### PR DESCRIPTION
**Pull request by Youakeem**
## Describe your changes
This PR is a bit strange, it was the first step and that's how it came out.

It uses `useShopSession` directly inside `CartEntries` and support default open state for product cards.

## Checklist before requesting a review

- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by Youakeem** [comment]
* **#4777** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4777?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4776** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4776?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4775** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4775?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4774** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4774?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4773** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4773?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4772** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4772?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Youakeem and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alebedev — APPROVED** [review]

**Review by guilhermespopolin — APPROVED** [review]
Just so I understand, what's the benefit of directly accessing shopSession in cart entries? It was designed to receive it as props so it's consumer - CheckoutPage - can renders a loading indicator while shopSession isn't available and inside CartEntries we don't need to write code checking the existence of shopSesion.

**Comment by Youakeem** [comment]
### Merge activity

* **Oct 8, 3:30 AM EDT**: @Youakeem started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/4772).

**Comment by Youakeem** [comment]
> Just so I understand, what's the benefit of directly accessing shopSession in cart entries? It was designed to receive it as props so it's consumer - CheckoutPage - can renders a loading indicator while shopSession isn't available and inside CartEntries we don't need to write code checking the existence of shopSesion.

I totally missed this comment, sorry! The main benefit/idea is to treat the `useShopSession` as a 'source of truth' for the shop session. I had previously noticed shopSession being passed down multiple levels which was a bit confusing and hard to follow.

**Pull request merged**
