### PR TITLE
Improve types for Emotion theme.space property

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Add t-shirt sizes for space property in Emotion theme.

## Justify why they are needed

This should work the same as for other properties I think.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1193** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1193" target="_blank">Graphite</a> 
    * **PR #1194** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1194" target="_blank">Graphite</a>  👈
      * **PR #1195** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1195" target="_blank">Graphite</a> 
        * **PR #1196** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1196" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1194?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Nice!

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: 2p15yc9KoO3nPlDemyGK.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1194)

**Comment by KarnellSchultz** [comment]
Question about the use of these tokens. 

Do we want to use these two styles of using tokens interchangeably? 

i.e. `space[0]` & `space.none` 

Not the biggest deal but thinking it'd be simpler to use one or the other, what say you?

**Review by KarnellSchultz — APPROVED** [review]

**Pull request merged**
