### PR TITLE
Extract theme.transitions.hover, apply hover styles to section triggers on product page

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Apply same transition rules to hover effects

Perhaps we should use Button more liberally instead, but it feels like too big refactoring for now

## Justify why they are needed

Design consistency

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1674** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1674" target="_blank">Graphite</a> 
    * **PR #1677** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1677" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1677?utm_source=stack-comment).

**Review by robinandeer — CHANGES_REQUESTED** [review]
Nice refactor -- just update the imports so we don't do it across packages

**Review by robinandeer — APPROVED** [review]
Looks great!

**Comment by alebedev** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Job ID: RBUii9nNjCx3ZvpFHXuD.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1677)

**Pull request merged**
