### PR TITLE
App Router: include global styles

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Include Global Emotion styles in App Router pages

## Justify why they are needed

Resets etc.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2874** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2874" target="_blank">Graphite</a> 
    * **PR #2875** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2875" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2875?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
nice!

**Review by guilhermespopolin — APPROVED** [review]

**Comment by robinandeer** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2875) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Comment by robinandeer** [comment]
@robinandeer merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2875).

**Pull request merged**
