### PR TITLE
Fix deserializing stepper input

### PR DESCRIPTION
**Pull request by alebedev**
## Describe your changes

Fix stepper field behavior when non-empty initial value was provided.  It took 2 as string ("2") and then button behaved like "2" + 1 = "21"

## Justify why they are needed

Fix co-insured field behavior when editing previously entered value

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by alebedev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2789** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2789" target="_blank">Graphite</a> 
    * **PR #2792** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2792" target="_blank">Graphite</a> 
      * **PR #2800** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2800" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2800?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Ohhh nice catch! Damn JS

**Review by guilhermespopolin — APPROVED** [review]

**Comment by alebedev** [comment]
[Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2800) rebased this pull request as part of a merge.

**Comment by alebedev** [comment]
@alebedev merged this pull request with [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/2800).

**Pull request merged**
