### PR TITLE
Center label text in TextField

### PR DESCRIPTION
**Pull request by robinandeer**
## Describe your changes

Quick fix. See title.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1301** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1301" target="_blank">Graphite</a> 
    * **PR #1302** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1302" target="_blank">Graphite</a> 
      * **PR #1304** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1304" target="_blank">Graphite</a>  👈
        * **PR #1305** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1305" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1304?utm_source=stack-comment).

**Comment by robinandeer** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1301** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1301" target="_blank">Graphite</a> 
    * **PR #1302** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1302" target="_blank">Graphite</a> 
      * **PR #1304** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1304" target="_blank">Graphite</a>  👈
        * **PR #1305** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1305" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1304?utm_source=stack-comment).

**Review by alebedev — APPROVED** [review]
Looks good

**Review by KarnellSchultz — APPROVED** [review]

**Comment by robinandeer** [comment]
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: gqYL6BIeAxEUO9tXGd8T.
See details on [graphite.dev](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/1304)

**Pull request merged**
