### PR TITLE
Update asset domain for images

### PR DESCRIPTION
**Pull request by gustaveen**
## Describe your changes
Use assets.hedvig.com as domain for assets, update according to this guide in CloudFront and Route 53 https://www.storyblok.com/docs/custom-assets-domain

- Use img src function to use Hedvig domain for images 

## Justify why they are needed
SEO and enable instant downloads of images

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by gustaveen** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3188** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3188" target="_blank">Graphite</a> 
    * **PR #3189** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3189" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3189?utm_source=stack-comment).

**Review by robinandeer — APPROVED** [review]
Great stuff!

I wonder if there's any way to centralize this 🤔

- Transform the response after we fetch from CMS
- Build it into some wrapper for Image-component and replace it there

Added via Giphy

**Comment by gustaveen** [comment]
> Great stuff!
> 
> I wonder if there's any way to centralize this 🤔
> 
> * Transform the response after we fetch from CMS
> * Build it into some wrapper for Image-component and replace it there
> 


Thanks! Yes! Let's centralize it in a component 🙌

**Comment by gustaveen** [comment]
### Merge Activity

* **Sep 13, 5:16 AM**: @gustaveen started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/racoon/3189).

**Pull request merged**
